/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JGEdIFROFRP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function list() {
  return (
    <div className="flex items-center justify-between bg-card p-4 rounded-md shadow-sm">
      <div className="grid gap-1.5">
        <h4 className="text-lg font-medium">Redesign website homepage</h4>
        <p className="text-sm text-muted-foreground">Update the homepage design to be more modern and engaging.</p>
      </div>
      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm">
          Update
        </Button>
        <Button variant="destructive" size="sm">
          Delete
        </Button>
      </div>
    </div>
  )
}
